### ISSUE TITLE
Same job get paused with error

### ISSUE THREAD

**Issue by MasRIS** [microsoft/Recurring-Integrations-Scheduler#118]
I am running the same Export job with Full push only on Data project, so I get the same data file every time. It runs successfully couple of times, and then get paused with an error. If I resume it, it may run successfully again. What can be the issue here?
D365 On premise 10.0.11, Update 35
RIS 3.2.2
Quartz.Core.JobRunShell - Job Export jobs.pool1 threw a JobExecutionException: 
Parameters: refire = False, unscheduleFiringTrigger = False, unscheduleAllTriggers = False 
 Quartz.JobExecutionException: Job: Export jobs.pool1 failed ---> Quartz.JobExecutionException: Export execution failed for job: Export jobs.pool1. Execution status: Failed
   at RecurringIntegrationsScheduler.Job.Export.<Process>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at RecurringIntegrationsScheduler.Job.Export.<Execute>d__5.MoveNext()
   --- End of inner exception stack trace ---
   at RecurringIntegrationsScheduler.Job.Export.<Execute>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Quartz.Core.JobRunShell.<Run>d__9.MoveNext() [See nested exception: Parameters: refire = False, unscheduleFiringTrigger = False, unscheduleAllTriggers = False 
 Quartz.JobExecutionException: Export execution failed for job: Export jobs.pool1. Execution status: Failed
   at RecurringIntegrationsScheduler.Job.Export.<Process>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at RecurringIntegrationsScheduler.Job.Export.<Execute>d__5.MoveNext()]

**Comment by TomekMelissa** [comment]
RIS is reporting an issue with an export job on D365 side. Look for clues on D365 side. In this context RIS is only the messenger.
