### ISSUE TITLE
Import using Package API jobs end in Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by MZade** [microsoft/Recurring-Integrations-Scheduler#119]
**Describe the bug**
Import using Package API jobs end in Object reference not set to an instance of an object.

**To Reproduce**
When using the RIS to have an import using Package API, the following error message is visible in the event log:
Object reference not set to an instance of an object.

**Expected behavior**
The files gets picked up and uploaded without this issue.

**Screenshots**
![image](https://user-images.githubusercontent.com/19854220/95050304-96ae0400-06eb-11eb-9cdc-02e82bc55b72.png)

![image](https://user-images.githubusercontent.com/19854220/95050466-e1c81700-06eb-11eb-88a5-8cab6fa12429.png)

**Recurring Integration Scheduler version (please complete the following information):**
 - Version 3.2.2.0

**Dynamics 365 version (please complete the following information):**
 - Application version 10.0.11
 - Platform version PU35

**Additional context**

RecurringIntegrationsScheduler.Job.Import - Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.
   at RecurringIntegrationsScheduler.Job.Import.<ProcessInputQueue>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at RecurringIntegrationsScheduler.Job.Import.<Process>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at RecurringIntegrationsScheduler.Job.Import.<Execute>d__9.MoveNext()

**Comment by MZade** [comment]
Hi, The issue was related to the fact that the related user in D365FO was disabled. After enabeling the related user in D365FO it works back properly.
To be clear, this is the user related to the Azure A/D Application in D365FO.

**Comment by MZade** [comment]
Hi, The issue was related to the fact that the related user in D365FO was disabled. After enabeling the related user in D365FO it works back properly.
To be clear, this is the user related to the Azure A/D Application in D365FO.
