### ISSUE TITLE
Import job - questions

### ISSUE THREAD

**Issue by fhburney** [Microsoft/Recurring-Integrations-Scheduler#52]
I can not get the import job to work, I have following setup.
1. I created a template file in D365, exampled 140-Customers, which has customer entities. (Customers V3)
2. Then I downloaded that template file.
3. Now in the input folder I dropped the file called Customers V3.xlsx
4. In the file schedule, I did the following setup
5. Its not picking the file up, not sure what am I missing here. ?

![image](https://user-images.githubusercontent.com/28990985/42183030-2d159886-7df5-11e8-8637-ffd9b1fc2003.png)

**Comment by TomekMelissa** [comment]
The user on your screenshot is admin@contoso.com I understand this is only for demonstration purpose and in fact you are using valid user for your instance.
Btw. I will work on the resolution/scaling issue soon :)

**Comment by fhburney** [comment]
How dumb of me of not setting the correct user, fixed that. 

![image](https://user-images.githubusercontent.com/28990985/42186617-336acb36-7e02-11e8-8bae-ecd37abc8afa.png)

Okay so still having a issue, any idea, its just customer file, i do not have all the field in the entity but I have all the nessary one. Also this is using the data template I created and its not the template you can generate by setting a export project do the fields and export the data package and then delete the file from the zip

![image](https://user-images.githubusercontent.com/28990985/42186696-793f8c78-7e02-11e8-9ef6-f3924e118bba.png)

![image](https://user-images.githubusercontent.com/28990985/42186714-84390168-7e02-11e8-9587-9b11bc5d00fb.png)

**Comment by TomekMelissa** [comment]
This is hoo you prepare template file #2

**Comment by fhburney** [comment]
@TomekMelissa 

Thanks still getting a errors, here is my setup, followed exactly how it is explained

![image](https://user-images.githubusercontent.com/28990985/42191294-fe9c280e-7e16-11e8-8bc8-dab81c7e77e2.png)


This what I am getting in log file


Quartz.Core.JobRunShell - Job Import jobs.CustImport threw a JobExecutionException: 
Parameters: refire = False, unscheduleFiringTrigger = False, unscheduleAllTriggers = False 
 Quartz.JobExecutionException: Import job: Import jobs.CustImport failed ---> System.ArgumentException: Empty path name is not legal.
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path)
   at RecurringIntegrationsScheduler.Job.Import.GetFileNameInPackage()
   at RecurringIntegrationsScheduler.Job.Import.<ProcessInputQueue>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at RecurringIntegrationsScheduler.Job.Import.<Process>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at RecurringIntegrationsScheduler.Job.Import.<Execute>d__10.MoveNext()
   --- End of inner exception stack trace ---
   at RecurringIntegrationsScheduler.Job.Import.<Execute>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Quartz.Core.JobRunShell.<Run>d__9.MoveNext() [See nested exception: System.ArgumentException: Empty path name is not legal.
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path)
   at RecurringIntegrationsScheduler.Job.Import.GetFileNameInPackage()
   at RecurringIntegrationsScheduler.Job.Import.<ProcessInputQueue>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at RecurringIntegrationsScheduler.Job.Import.<Process>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at RecurringIntegrationsScheduler.Job.Import.<Execute>d__10.MoveNext()]

**Comment by MZade** [comment]
My understanding is that for composite data entities, you should not set the "Overwrite data project definition". Just leave it unchecked and try again...

**Comment by fhburney** [comment]
Thanks @MZade 

So the problem was, I unzipped the orginal zip file, deleted the data file and zipped it backup, winzip for some reason created another sub folder and places the files there. So once I fixed that I did pass those errors, now I am getting this error

RecurringIntegrationsScheduler.Job.Import - Method GetAzureWriteUrl returned empty string


Also when I validate I do get this error

AAD authentication was successful
D365FO instance seems to be up and running.
Access to D365FO instance was successful.
Method GetAzureWriteUrl returned empty string. Check previous errors.Method GetMessageStatus returned empty string. KB4058074 is not installed.


I am using 8.0 update 15, interesting its missing a KB

**Comment by TomekMelissa** [comment]
This is not necessarily true... This validation only checks one particular request introduced in this KB. 
It fails, but previous one (GetAzureWriteURL) fails as well, so it looks like you have 7.2 instance pre PU5 which is not true... I will make some checks with 8.0 and will get back to you.

**Comment by AndreasHassing** [comment]
@fhburney is this a on-premises deployment?

**Comment by phillipsra16** [comment]
@MZade & @TomekMelissa 

I am seeing the same thing in 8.0 PU 15.  I receive the GetAzureWriteUrl error at both validate and when actually attempting to run jobs.

**Comment by fhburney** [comment]
@TomekMelissa 

I can confirm this is working with the latest release, thank you!

**Comment by RussKuksin** [comment]
Having similar issue. Ax version is 8.0 update 15 (7.0.4841.35234)
 Trying to "Validate" connection with service authentication and getting this in return:
"AAD authentication was successful
D365FO instance seems to be up and running.
AAD application is not mapped to a user or mapped user has insufficient privileges assigned.
Method GetAzureWriteUrl returned empty string. Check previous errors.Method GetMessageStatus returned empty string. KB4058074 is not installed."

And yet the setup on the AX side is done: 
![setup1](https://user-images.githubusercontent.com/43584248/46033296-1c3d5900-c0bb-11e8-98cb-a62e681bfe26.PNG)

**Comment by abhishekbaluni** [comment]
have similar issue , when hit validate , the parameters am getting the following error 

AAD authentication was successful
D365FO instance seems to be up and running.
Access to D365FO instance was successful.
Method GetAzureWriteUrl returned empty string. Check previous errors.Method GetMessageStatus returned empty string. Check previous errors.

have added the aad application
