### ISSUE TITLE
Export Job

### ISSUE THREAD

**Issue by fhburney** [Microsoft/Recurring-Integrations-Scheduler#53]
I am on version 8, update 15.

I can not get the export job to work, here are the error

RecurringIntegrationsScheduler.Job.Export - Job: Export jobs.CustImportTest. Download failure. BadRequest
System.Exception: Job: Export jobs.CustImportTest. Download failure. BadRequest
   at RecurringIntegrationsScheduler.Job.Export.<Process>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at RecurringIntegrationsScheduler.Job.Export.<Execute>d__6.MoveNext()

Looking at network.log

System.Net Information: 0 : [16784] ConnectStream#35428172::ConnectStream(Buffered 6141 bytes.)
System.Net Information: 0 : [16784] Associating HttpWebRequest#21815586 with ConnectStream#35428172
System.Net Information: 0 : [16784] Associating HttpWebRequest#21815586 with HttpWebResponse#28624768
System.Net Warning: 0 : [16784] HttpWebRequest#21815586::() - The remote server returned an error: (400) Bad Request.
System.Net Verbose: 0 : [16784] HttpWebRequest#21815586::EndGetResponse()
System.Net Verbose: 0 : [16784] Exiting HttpWebRequest#21815586::EndGetResponse() 	-> HttpWebResponse#28624768
System.Net.Http Verbose: 0 : [16784] HttpResponseMessage#28951958::.ctor(StatusCode: 400, ReasonPhrase: '')
System.Net.Http Verbose: 0 : [16784] Exiting HttpResponseMessage#28951958::.ctor() 
System.Net.Http Information: 0 : [16784] Associating HttpResponseMessage#28951958 with HttpRequestMessage#65266205
System.Net Verbose: 0 : [16784] HttpWebResponse#28624768::GetResponseStream()
System.Net Information: 0 : [16784] ContentLength=6141
System.Net Verbose: 0 : [16784] Exiting HttpWebResponse#28624768::GetResponseStream() 	-> ConnectStream#35428172
System.Net.Http Verbose: 0 : [16784] StreamContent#51528091::.ctor()
System.Net.Http Verbose: 0 : [16784] Exiting StreamContent#51528091::.ctor() 
System.Net.Http Information: 0 : [16784] Associating StreamContent#51528091 with WebExceptionWrapperStream#65777371
System.Net.Http Information: 0 : [16784] Associating HttpResponseMessage#28951958 with StreamContent#51528091
System.Net Verbose: 0 : [16784] ConnectStream#35428172::BeginRead()
System.Net Verbose: 0 : [16784] Exiting ConnectStream#35428172::BeginRead() 	-> BufferAsyncResult#42344745
System.Net Verbose: 0 : [16784] ConnectStream#35428172::EndRead()
System.Net Verbose: 0 : [16784] Exiting ConnectStream#35428172::EndRead() 	-> Int32#4096
System.Net Verbose: 0 : [16784] ConnectStream#35428172::BeginRead()
System.Net Verbose: 0 : [16784] Exiting ConnectStream#35428172::BeginRead() 	-> BufferAsyncResult#36106288
System.Net Verbose: 0 : [16784] ConnectStream#35428172::EndRead()
System.Net Verbose: 0 : [16784] Exiting ConnectStream#35428172::EndRead() 	-> Int32#2045
System.Net Verbose: 0 : [16784] ConnectStream#35428172::BeginRead()
System.Net Verbose: 0 : [16784] Exiting ConnectStream#35428172::BeginRead() 	-> NestedSingleAsyncResult#8305944
System.Net Verbose: 0 : [16784] ConnectStream#35428172::EndRead()
System.Net Verbose: 0 : [16784] Exiting ConnectStream#35428172::EndRead() 	-> Int32#0
System.Net Verbose: 0 : [16784] ConnectStream#35428172::Close()
System.Net Verbose: 0 : [16784] Exiting ConnectStream#35428172::Close() 
System.Net.Http Information: 0 : [16784] HttpClient#29811639 - Request for HttpRequestMessage#65266205 completed successfully. Returning response HttpResponseMessage#28951958: StatusCode: 400, ReasonPhrase: 'Bad Request', Version: 1.1, Content: System.Net.Http.StreamContent, Headers:
{
  Strict-Transport-Security: max-age=31536000; includeSubDomains
  Strict-Transport-Security: max-age=31536000; includeSubDomains
  OData-Version: 4.0
  ms-dyn-fqhn: soma-dev1-1-11323b74-f248-4f9a-82d9-5c2d434aa145
  ms-dyn-namespace: DynAXProd
  ms-dyn-tenant: default-lcs-11323b74-f248-4f9a-82d9-5c2d434aa145
  ms-dyn-role: dev
  ms-dyn-aid: 5e565990-131f-0003-4663-565e1f13d401
  X-Content-Type-Options: nosniff
  X-Frame-Options: SAMEORIGIN
  Date: Tue, 03 Jul 2018 22:52:27 GMT
  P3P: CP="No P3P policy defined.  Read the Microsoft privacy statement at https://go.microsoft.com/fwlink/?LinkId=271135"
  Server: Microsoft-IIS/10.0
  X-Powered-By: ASP.NET
  Content-Length: 6141
  Content-Type: application/json; odata.metadata=minimal
}
System.Net Verbose: 0 : [16784] HttpWebRequest#21815586::Abort()
System.Net Error: 0 : [16784] Exception in HttpWebRequest#21815586:: - The request was aborted: The request was canceled..
System.Net Verbose: 0 : [16784] Exiting HttpWebRequest#21815586::Abort() 
System.Net.Sockets Verbose: 0 : [16784] Socket#12966380::Dispose()

**Comment by fhburney** [comment]
BTW - the download job is working the export job is the one with issue.

**Comment by fhburney** [comment]
BTW - the download job is working the export job is the one with issue.
