### ISSUE TITLE
What is the 'Entryname' parameter?

### ISSUE THREAD

**Issue by jminquette** [Microsoft/Recurring-Integrations-Scheduler#65]
Hi,
 I'm trying to integrate datas in D365FO using Data management.
 I've setup the Recurring Integration Scheduler 2.4, providing all needed parameters i think :-).
 I've created an Import job (named "Import Salariés") using a data package. The package template (generated from D365FO) is setup on the RIS job.
 When i run the job, i get the following exception on the event vewier of RIS app.

Quartz.Core.JobRunShell - Job Import jobs.Import Salariés threw a JobExecutionException:
 Parameters: refire = False, unscheduleFiringTrigger = False, unscheduleAllTriggers = False
 Quartz.JobExecutionException: Import job: Import jobs.Import Salariés failed ---> System.ArgumentNullException: Value cannot be null.
 Parameter name: **entryName**
 at System.IO.Compression.ZipArchive.GetEntry(String entryName)
 at RecurringIntegrationsScheduler.Job.Import.d__12.MoveNext()
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at RecurringIntegrationsScheduler.Job.Import.d__11.MoveNext()
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at RecurringIntegrationsScheduler.Job.Import.d__10.MoveNext()
 --- End of inner exception stack trace ---
 at RecurringIntegrationsScheduler.Job.Import.d__10.MoveNext()
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at Quartz.Core.JobRunShell.d__9.MoveNext() [See nested exception: System.ArgumentNullException: Value cannot be null.
 Parameter name: entryName
 at System.IO.Compression.ZipArchive.GetEntry(String entryName)
 at RecurringIntegrationsScheduler.Job.Import.d__12.MoveNext()
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at RecurringIntegrationsScheduler.Job.Import.d__11.MoveNext()
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at RecurringIntegrationsScheduler.Job.Import.d__10.MoveNext()]

**Comment by TomekMelissa** [comment]
please share your template file

**Comment by TomekMelissa** [comment]
Use latest version and double check your manifest file. Remember that RIS does not support multiple entities in one package that it creates.

**Comment by jminquette** [comment]
Hi,
Thanks a lot for that feedback. 
I've several Entites in my package. That was the problem.
Do you know how to figure out this issue by keeping multiple entities in one package?
Except RIS, is they another free application?

**Comment by TomekMelissa** [comment]
You need to create package earlier using some other tool than RIS. Then RIS can send it.

**Comment by PatrikLc** [comment]
Which other tools are available to create such a package with multiple entities in it?

**Comment by TomekMelissa** [comment]
I am not aware of such tools. You need to create them for your scenario.
