### ISSUE TITLE
Stack trace: Error while copying content to a stream

### ISSUE THREAD

**Issue by MZade** [microsoft/Recurring-Integrations-Scheduler#89]
### Expected behavior and actual behavior.
Files should be uploaded without any stack trace/interruptions

### Steps to reproduce the problem.
1. Use sales orders composite V3 data entity
2. Create a data project and an import job
3. Create 500 files
4. Start the upload and wait, sometimes this issue is happening

### Specifications like the version of RIS and platform and application version of D365FO.
**RIS version 2.7.1.0**
**D3FO platform version PU27**
**D3FO application version 7.3**

### STACK TRACE
RecurringIntegrationsScheduler.Job.Import - Error while copying content to a stream. System.Net.Http.HttpRequestException: Error while copying content to a stream. ---> System.ObjectDisposedException: Cannot access a closed file. at System.IO.__Error.FileNotOpen() at System.IO.FileStream.BeginRead(Byte[] array, Int32 offset, Int32 numBytes, AsyncCallback userCallback, Object stateObject) at System.Net.Http.StreamToStreamCopy.StartRead() --- End of inner exception stack trace --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Polly.Retry.AsyncRetryEngine.<ImplementationAsync>d__0`1.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Polly.AsyncPolicy.<ExecuteAsync>d__21`1.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at RecurringIntegrationsScheduler.Common.Helpers.HttpClientHelper.<UploadContentsToBlob>d__20.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at RecurringIntegrationsScheduler.Job.Import.<ProcessInputQueue>d__12.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at RecurringIntegrationsScheduler.Job.Import.<Process>d__11.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at RecurringIntegrationsScheduler.Job.Import.<Execute>d__10.MoveNext()

**Comment by muehe44** [comment]
Hello Mehrdad,
we have a similar problem.
We are using also an import for the sales order with plattform update 28.

The system runs pretty well, but after two month it runs into an error. This error happen only on the server where the RIS runs. We tried to remove RIS and install it again, but without success. Still the same error. If we run it on an other server it will work. It is also not possible to run it again on the first server with that error. 
Here is the error:
Quartz.Core.JobRunShell - Job ExportJobs.LIVE_DESADV_241 threw a JobExecutionException: 
Parameters: refire = False, unscheduleFiringTrigger = False, unscheduleAllTriggers = False 
 Quartz.JobExecutionException: Import job: ExportJobs.LIVE_DESADV_241 failed ---> System.IO.IOException: The file exists.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Path.InternalGetTempFileName(Boolean checkHost)
   at RecurringIntegrationsScheduler.Job.Import.<ProcessInputQueue>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at RecurringIntegrationsScheduler.Job.Import.<Process>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at RecurringIntegrationsScheduler.Job.Import.<Execute>d__10.MoveNext()
   --- End of inner exception stack trace ---
   at RecurringIntegrationsScheduler.Job.Import.<Execute>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Quartz.Core.JobRunShell.<Run>d__9.MoveNext() [See nested exception: System.IO.IOException: The file exists.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Path.InternalGetTempFileName(Boolean checkHost)
   at RecurringIntegrationsScheduler.Job.Import.<ProcessInputQueue>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at RecurringIntegrationsScheduler.Job.Import.<Process>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at RecurringIntegrationsScheduler.Job.Import.<Execute>d__10.MoveNext()]

**Comment by TomekMelissa** [comment]
@muehe44 In your case you probalby hit the limit of temporary files. RIS is using Path.GetTempFileName to generate temporary files needed for operations on package template. This API has limit of 65536 files after that it will start producing duplicates. I will change file name generation function, but at the same time you need to make sure you are cleaning your temp folder. [See this for more info.](https://stackoverflow.com/questions/18350699/system-io-ioexception-the-file-exists-when-using-system-io-path-gettempfilena)
